@echo off
rem Script generated by the R for MOVES
rem -----------------------------------------------------------
echo Changing to the MOVES folder and compiling code...
cd C:\Users\Public\EPA\MOVES\MOVES2014b
call setenv.bat
call ant compile
rem -----------------------------------------------------------
echo Running test_11001_2017_test.mrs
java -Xmx512M gov.epa.otaq.moves.master.commandline.MOVESCommandLine -r "test_files\ozn_dc_2017_naaq_out.mrs"
